[env:ES3C28P]
board = esp32-s3-devkitc-1
board_build.partitions = partitions_8MB.csv
board_build.arduino.memory_type = qio_qspi
board_build.f_flash = 80000000L
board_build.f_cpu = 240000000L
board_build.flash_mode = qio

build_flags = 
    ${env.build_flags}
    -D ES3C28P=1
    -D DEVICE_NAME=\"ES3C28P\"
    -D BOARD_HAS_PSRAM=1
    -D CONFIG_SPIRAM_SUPPORT=1
    
    ; Direct Include for Arduino Pins Directory
    -I"${platformio.packages_dir}/framework-arduinoespressif32/variants/esp32s3"
    
    ; Standard SPI Pins Definition
    -D PIN_SPI_SCK=12
    -D PIN_SPI_MISO=13
    -D PIN_SPI_MOSI=11
    -D PIN_SPI_SS=10
    
    ; Global & Project Utils SPI Mapping
    -D SPI_SCK_PIN=12
    -D SPI_MOSI_PIN=11
    -D SPI_MISO_PIN=13
    -D SPI_SS_PIN=10
    
    ; BadUSB Serial Pins
    -D BAD_RX=44
    -D BAD_TX=43
    
    ; CC1101 Sub-GHz Module Pins (Transceiver)
    -D CC1101_CS_PIN=10
    -D CC1101_GDO0_PIN=4
    -D CC1101_GDO2_PIN=5
    
    ; NRF24 / RF Module Pins
    -D NRF24_CS_PIN=10
    -D NRF24_CE_PIN=6
    
    ; Infrared (IR) Pins
    -D IR_RX_PIN=14
    -D IR_TX_PIN=15
    
    ; Speaker / Buzzer Pins
    -D SPEAKER_PIN=16
    -D BUZZER_PIN=16
    
    ; Display Driver Setup
    -D USER_SETUP_LOADED=1
    -D ILI9341_2_DRIVER=1
    -D TFT_INVERSION_ON=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=320
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_CS=10
    -D TFT_DC=46
    -D TFT_RST=-1
    -D TFT_BL=45
    -D TFT_BACKLIGHT_ON=HIGH
    -D SMOOTH_FONT=1
    -D SPI_FREQUENCY=40000000
    -D SPI_READ_FREQUENCY=20000000

    ; Resistive Touch (SPI XPT2046)
    -D TOUCH_CS=17
    -D SPI_TOUCH_FREQUENCY=2500500

    ; Storage Mode
    -D USE_SD_MMC

lib_deps = 
    ${env.lib_deps}
